// Generated by scripts/gen_parameters.mjs from parameters.js. Do not edit.
export interface ParameterDefinition {
  readonly id: number;
  /** Value applied for this field when a preset omits it. */
  readonly default: number;
  readonly min: number;
  readonly max: number;
  readonly step: number;
  readonly unit: string;
  readonly values?: Readonly<Record<string, number>>;
  /** Preferred playground ceiling; the control expands for a preset above it. */
  readonly editorMax?: number;
}

export declare const SHAPE: { readonly saw: 0; readonly pulse: 1; readonly triangle: 2; };
export declare const FILTER: { readonly ladderLp: 0; readonly diodeLp: 1; readonly svfLp: 2; readonly svfBp: 3; readonly svfHp: 4; readonly svfNotch: 5; };

export declare const PARAMETERS: {
  readonly shape: { readonly id: 0; readonly default: 0; readonly min: 0; readonly max: 2; readonly step: 1; readonly unit: "enum"; readonly values: { readonly saw: 0; readonly pulse: 1; readonly triangle: 2; }; };
  readonly filterKind: { readonly id: 37; readonly default: 0; readonly min: 0; readonly max: 5; readonly step: 1; readonly unit: "enum"; readonly values: { readonly ladderLp: 0; readonly diodeLp: 1; readonly svfLp: 2; readonly svfBp: 3; readonly svfHp: 4; readonly svfNotch: 5; }; };
  readonly unison: { readonly id: 31; readonly default: 2; readonly min: 1; readonly max: 7; readonly step: 1; readonly unit: "voices"; };
  readonly detuneCents: { readonly id: 2; readonly default: 8; readonly min: 0; readonly max: 1400; readonly step: 0.5; readonly unit: "cents"; readonly editorMax: 40; };
  readonly pulseWidth: { readonly id: 1; readonly default: 0.5; readonly min: 0.05; readonly max: 0.95; readonly step: 0.01; readonly unit: "ratio"; };
  readonly subLevel: { readonly id: 3; readonly default: 0.25; readonly min: 0; readonly max: 1; readonly step: 0.01; readonly unit: "linear gain"; };
  readonly noiseLevel: { readonly id: 4; readonly default: 0; readonly min: 0; readonly max: 1; readonly step: 0.01; readonly unit: "linear gain"; };
  readonly glide: { readonly id: 32; readonly default: 0; readonly min: 0; readonly max: 0.4; readonly step: 0.005; readonly unit: "seconds"; };
  readonly cutoffHz: { readonly id: 5; readonly default: 1200; readonly min: 60; readonly max: 8000; readonly step: 10; readonly unit: "Hz"; };
  readonly resonance: { readonly id: 6; readonly default: 0.3; readonly min: 0; readonly max: 1; readonly step: 0.01; readonly unit: "ratio"; };
  readonly drive: { readonly id: 7; readonly default: 1.2; readonly min: 0.5; readonly max: 4; readonly step: 0.05; readonly unit: "times"; };
  readonly envAmount: { readonly id: 8; readonly default: 2400; readonly min: 0; readonly max: 8000; readonly step: 50; readonly unit: "Hz"; };
  readonly keyTrack: { readonly id: 9; readonly default: 0.35; readonly min: 0; readonly max: 1; readonly step: 0.01; readonly unit: "ratio"; };
  readonly velToCutoff: { readonly id: 18; readonly default: 2000; readonly min: 0; readonly max: 6000; readonly step: 50; readonly unit: "Hz"; };
  readonly ampAttack: { readonly id: 10; readonly default: 0.005; readonly min: 0.001; readonly max: 2; readonly step: 0.001; readonly unit: "seconds"; };
  readonly ampDecay: { readonly id: 11; readonly default: 0.25; readonly min: 0.005; readonly max: 2; readonly step: 0.005; readonly unit: "seconds"; };
  readonly ampSustain: { readonly id: 12; readonly default: 0.7; readonly min: 0; readonly max: 1; readonly step: 0.01; readonly unit: "ratio"; };
  readonly ampRelease: { readonly id: 13; readonly default: 0.25; readonly min: 0.005; readonly max: 3; readonly step: 0.005; readonly unit: "seconds"; };
  readonly fltAttack: { readonly id: 14; readonly default: 0.002; readonly min: 0.001; readonly max: 2; readonly step: 0.001; readonly unit: "seconds"; };
  readonly fltDecay: { readonly id: 15; readonly default: 0.3; readonly min: 0.005; readonly max: 2; readonly step: 0.005; readonly unit: "seconds"; };
  readonly fltSustain: { readonly id: 16; readonly default: 0.3; readonly min: 0; readonly max: 1; readonly step: 0.01; readonly unit: "ratio"; };
  readonly fltRelease: { readonly id: 17; readonly default: 0.25; readonly min: 0.005; readonly max: 3; readonly step: 0.005; readonly unit: "seconds"; };
  readonly lfoRate: { readonly id: 33; readonly default: 5; readonly min: 0.05; readonly max: 16; readonly step: 0.05; readonly unit: "Hz"; };
  readonly lfoToPitch: { readonly id: 34; readonly default: 0; readonly min: 0; readonly max: 60; readonly step: 1; readonly unit: "cents"; };
  readonly lfoToCutoff: { readonly id: 35; readonly default: 0; readonly min: 0; readonly max: 3000; readonly step: 25; readonly unit: "Hz"; };
  readonly lfoToPwm: { readonly id: 36; readonly default: 0; readonly min: 0; readonly max: 0.45; readonly step: 0.01; readonly unit: "ratio"; };
  readonly chorusMix: { readonly id: 22; readonly default: 0; readonly min: 0; readonly max: 1; readonly step: 0.01; readonly unit: "ratio"; };
  readonly chorusRate: { readonly id: 20; readonly default: 0.6; readonly min: 0.05; readonly max: 6; readonly step: 0.01; readonly unit: "Hz"; };
  readonly chorusDepth: { readonly id: 21; readonly default: 3; readonly min: 0; readonly max: 12; readonly step: 0.1; readonly unit: "milliseconds"; };
  readonly delayMix: { readonly id: 23; readonly default: 0; readonly min: 0; readonly max: 1; readonly step: 0.01; readonly unit: "ratio"; };
  readonly delayTime: { readonly id: 24; readonly default: 0.25; readonly min: 0.02; readonly max: 1; readonly step: 0.005; readonly unit: "seconds"; };
  readonly delayFeedback: { readonly id: 25; readonly default: 0.35; readonly min: 0; readonly max: 0.92; readonly step: 0.01; readonly unit: "ratio"; };
  readonly delayTone: { readonly id: 26; readonly default: 3200; readonly min: 400; readonly max: 16000; readonly step: 100; readonly unit: "Hz"; };
  readonly reverbMix: { readonly id: 27; readonly default: 0; readonly min: 0; readonly max: 1; readonly step: 0.01; readonly unit: "ratio"; };
  readonly reverbSize: { readonly id: 28; readonly default: 0.6; readonly min: 0; readonly max: 1; readonly step: 0.01; readonly unit: "ratio"; };
  readonly reverbDamp: { readonly id: 29; readonly default: 4200; readonly min: 800; readonly max: 14000; readonly step: 100; readonly unit: "Hz"; };
  readonly reverbPredelay: { readonly id: 30; readonly default: 18; readonly min: 0; readonly max: 100; readonly step: 1; readonly unit: "milliseconds"; };
  readonly stereoWidth: { readonly id: 38; readonly default: 0.7; readonly min: 0; readonly max: 1; readonly step: 0.01; readonly unit: "ratio"; };
  readonly syncRatio: { readonly id: 39; readonly default: 1; readonly min: 1; readonly max: 8; readonly step: 0.05; readonly unit: "ratio"; };
  readonly pitchEnvAmount: { readonly id: 40; readonly default: 0; readonly min: -36; readonly max: 36; readonly step: 1; readonly unit: "semitones"; };
  readonly pitchEnvDecay: { readonly id: 41; readonly default: 0.08; readonly min: 0.005; readonly max: 1; readonly step: 0.005; readonly unit: "seconds"; };
  readonly lfo2Rate: { readonly id: 42; readonly default: 3; readonly min: 0.05; readonly max: 16; readonly step: 0.05; readonly unit: "Hz"; };
  readonly lfo2ToCutoff: { readonly id: 43; readonly default: 0; readonly min: 0; readonly max: 4000; readonly step: 25; readonly unit: "Hz"; };
  readonly lfo2ToPitch: { readonly id: 44; readonly default: 0; readonly min: 0; readonly max: 12; readonly step: 0.1; readonly unit: "semitones"; };
  readonly noiseColor: { readonly id: 45; readonly default: 0; readonly min: 0; readonly max: 1; readonly step: 0.01; readonly unit: "ratio (white to pink)"; };
  readonly oscLevel: { readonly id: 46; readonly default: 1; readonly min: 0; readonly max: 1; readonly step: 0.01; readonly unit: "linear gain"; };
  readonly gain: { readonly id: 19; readonly default: 0.32; readonly min: 0; readonly max: 0.85; readonly step: 0.01; readonly unit: "linear gain"; readonly editorMax: 0.8; };
};

/** Patch parameter names accepted by `Engine.setParam`. */
export type ParamName = keyof typeof PARAMETERS;

export declare const PARAM: {
  readonly [Name in ParamName]: (typeof PARAMETERS)[Name]["id"];
};

export declare const PARAM_DEFAULTS: {
  readonly [Name in ParamName]: (typeof PARAMETERS)[Name]["default"];
};
