// The patch bank. PRINCIPLES #1: curation is the product -- these values ARE the work.
//
// Categories follow the General MIDI sound set, a published open specification, and the
// structural conventions of subtractive synthesis, which are textbook. Values are designed
// against THIS engine's controls; nothing here is transcribed from anyone's factory bank.
// See agentic-docs/licensing.md, "Patch design -- what may be learned from, and what may not".
//
// EVERY patch is merged over DEFAULTS before it is sent. The engine is stateful, so a
// partial patch would inherit whatever the last one set -- which is how an acid line once
// ended up playing through a chorus. Completeness is structural here, not a review habit.

import { FILTER, PARAM_DEFAULTS, SHAPE } from "./parameters.js";

/** Neutral starting point. Any field a patch omits is RESET to this, never left behind. */
export const DEFAULTS = PARAM_DEFAULTS;

/** `group` picks the demo pattern: a pad and a bassline do not want the same notes. */
export const PRESETS = {
  "analog-bass": { label: "Analog bass", group: "bass",
    blurb: "Round, punchy, sits under everything.",
    params: { shape: SHAPE.saw, filterKind: FILTER.ladderLp, unison: 2, detuneCents: 6, subLevel: 0.6, cutoffHz: 420, resonance: 0.28, drive: 1.6, envAmount: 2200, keyTrack: 0.25, ampDecay: 0.3, ampSustain: 0.6, ampRelease: 0.14, fltDecay: 0.22, fltSustain: 0.12, velToCutoff: 1800, reverbMix: 0.05, reverbSize: 0.35, gain: 0.435 , stereoWidth: 0.2 } },
  "acid": { label: "Acid", group: "bass",
    blurb: "Squelch. The filter is the instrument.",
    params: { shape: SHAPE.saw, filterKind: FILTER.diodeLp, unison: 1, subLevel: 0.18, cutoffHz: 170, resonance: 0.88, drive: 2.6, envAmount: 3400, keyTrack: 0.15, glide: 0.055, ampDecay: 0.5, ampSustain: 0.85, ampRelease: 0.07, fltDecay: 0.17, fltSustain: 0, velToCutoff: 2600, delayMix: 0.18, delayTime: 0.187, delayFeedback: 0.32, reverbMix: 0.1, gain: 0.072 , stereoWidth: 0.15 } },
  "kick-bass": { label: "Kick bass", group: "bass",
    blurb: "Pitch drops into the note. Percussive enough to be a drum.",
    params: { shape: SHAPE.triangle, filterKind: FILTER.ladderLp, unison: 1, subLevel: 0.7,
      cutoffHz: 220, resonance: 0.15, drive: 1.8, envAmount: 700, keyTrack: 0.1,
      pitchEnvAmount: 26, pitchEnvDecay: 0.045,
      ampAttack: 0.001, ampDecay: 0.28, ampSustain: 0, ampRelease: 0.1,
      fltDecay: 0.12, fltSustain: 0, velToCutoff: 600, stereoWidth: 0, gain: 0.479 } },

  "sub-bass": { label: "Sub bass", group: "bass",
    blurb: "Almost no harmonics. Felt more than heard.",
    params: { shape: SHAPE.triangle, filterKind: FILTER.ladderLp, unison: 1, subLevel: 0.85, cutoffHz: 180, resonance: 0.05, drive: 1.0, envAmount: 300, keyTrack: 0.1, ampAttack: 0.008, ampDecay: 0.4, ampSustain: 0.85, ampRelease: 0.2, fltSustain: 0.6, velToCutoff: 400, gain: 0.264 , stereoWidth: 0.0 } },
  "growl-bass": { label: "Growl bass", group: "bass",
    blurb: "Fast filter wobble. Aggressive and moving.",
    params: { shape: SHAPE.saw, filterKind: FILTER.ladderLp, unison: 2, detuneCents: 14, subLevel: 0.4, cutoffHz: 300, resonance: 0.7, drive: 3.0, envAmount: 1800, lfoRate: 7.5, lfoToCutoff: 1400, ampSustain: 0.85, ampRelease: 0.1, fltDecay: 0.25, fltSustain: 0.4, velToCutoff: 1600, gain: 0.289 , stereoWidth: 0.35 } },
  "pluck-bass": { label: "Pluck bass", group: "bass",
    blurb: "No sustain at all. Percussive and dry.",
    params: { shape: SHAPE.saw, filterKind: FILTER.ladderLp, unison: 1, subLevel: 0.45, cutoffHz: 500, resonance: 0.55, drive: 1.5, envAmount: 3000, ampDecay: 0.2, ampSustain: 0, ampRelease: 0.09, fltDecay: 0.1, fltSustain: 0, velToCutoff: 2400, gain: 0.85 , stereoWidth: 0.2 } },
  "wide-bass": { label: "Wide bass", group: "bass",
    blurb: "Heavily detuned pair, slow sweep. Wide and unstable.",
    params: { shape: SHAPE.saw, filterKind: FILTER.svfLp, unison: 2, detuneCents: 34, subLevel: 0.3, cutoffHz: 480, resonance: 0.4, drive: 1.4, envAmount: 900, lfoRate: 0.22, lfoToCutoff: 500, ampAttack: 0.02, ampSustain: 0.9, ampRelease: 0.3, fltSustain: 0.7, velToCutoff: 900, gain: 0.203 , stereoWidth: 0.85 } },
  "square-lead": { label: "Square lead", group: "lead",
    blurb: "Hollow and vocal. The oldest lead there is.",
    params: { shape: SHAPE.pulse, filterKind: FILTER.ladderLp, unison: 1, pulseWidth: 0.5, subLevel: 0.2, cutoffHz: 1900, resonance: 0.25, envAmount: 1600, keyTrack: 0.6, ampAttack: 0.008, ampSustain: 0.85, ampRelease: 0.18, fltSustain: 0.5, lfoRate: 5.4, lfoToPitch: 7, reverbMix: 0.22, delayMix: 0.2, gain: 0.16 } },
  "saw-lead": { label: "Saw lead", group: "lead",
    blurb: "Bright and direct. Cuts without volume.",
    params: { shape: SHAPE.saw, filterKind: FILTER.ladderLp, unison: 2, detuneCents: 9, subLevel: 0.2, cutoffHz: 2200, resonance: 0.35, drive: 1.5, envAmount: 2000, keyTrack: 0.55, glide: 0.03, ampAttack: 0.01, ampSustain: 0.85, ampRelease: 0.2, fltSustain: 0.5, lfoRate: 5.2, lfoToPitch: 8, chorusMix: 0.3, delayMix: 0.28, reverbMix: 0.3, gain: 0.343 } },
  "supersaw": { label: "Supersaw", group: "lead",
    blurb: "Seven detuned saws. Wide enough to be its own chord.",
    params: { shape: SHAPE.saw, filterKind: FILTER.svfLp, unison: 7, detuneCents: 26, subLevel: 0.1, cutoffHz: 2600, resonance: 0.2, drive: 1.3, envAmount: 1800, keyTrack: 0.6, ampAttack: 0.012, ampDecay: 0.5, ampSustain: 0.85, ampRelease: 0.35, fltDecay: 0.6, fltSustain: 0.6, velToCutoff: 1800, reverbMix: 0.35, reverbSize: 0.7, delayMix: 0.22, gain: 0.152 , stereoWidth: 1.0 } },
  "sync-lead": { label: "Sync lead", group: "lead",
    blurb: "Hard sync. The pitch holds while the timbre tears upward.",
    params: { shape: SHAPE.saw, filterKind: FILTER.ladderLp, unison: 2, detuneCents: 6,
      subLevel: 0.1, cutoffHz: 3200, resonance: 0.25, drive: 1.6, envAmount: 1200,
      keyTrack: 0.5, syncRatio: 2.7, ampAttack: 0.008, ampSustain: 0.85,
      ampRelease: 0.2, fltSustain: 0.6, lfoRate: 0.35, lfoToCutoff: 600,
      stereoWidth: 0.4, reverbMix: 0.3, delayMix: 0.22, gain: 0.153 } },

  "fifths-lead": { label: "Fifths lead", group: "lead",
    blurb: "Two voices a fifth apart. Instantly bigger than one note.",
    params: { shape: SHAPE.saw, filterKind: FILTER.ladderLp, unison: 2, detuneCents: 1400, subLevel: 0.15, cutoffHz: 1800, resonance: 0.3, drive: 1.4, envAmount: 1800, keyTrack: 0.6, ampAttack: 0.01, ampSustain: 0.8, ampRelease: 0.2, fltSustain: 0.45, reverbMix: 0.25, gain: 0.314 } },
  "soft-lead": { label: "Soft lead", group: "lead",
    blurb: "Triangle through a gentle filter. Flute-ish.",
    params: { shape: SHAPE.triangle, filterKind: FILTER.svfLp, unison: 2, detuneCents: 5, subLevel: 0.15, cutoffHz: 2400, resonance: 0.12, drive: 1.0, envAmount: 900, keyTrack: 0.5, ampAttack: 0.06, ampSustain: 0.9, ampRelease: 0.3, fltAttack: 0.05, fltSustain: 0.7, lfoRate: 4.6, lfoToPitch: 6, chorusMix: 0.4, reverbMix: 0.4, gain: 0.184 } },
  "buzz-lead": { label: "Buzz lead", group: "lead",
    blurb: "Narrow pulse, hard drive. Nasal and rude.",
    params: { shape: SHAPE.pulse, filterKind: FILTER.diodeLp, unison: 2, detuneCents: 12, pulseWidth: 0.16, subLevel: 0.1, cutoffHz: 1500, resonance: 0.6, drive: 3.2, envAmount: 2400, keyTrack: 0.5, ampSustain: 0.85, ampRelease: 0.15, fltDecay: 0.25, fltSustain: 0.45, delayMix: 0.25, gain: 0.159 } },
  "pwm-lead": { label: "PWM lead", group: "lead",
    blurb: "Pulse width breathing under the note.",
    params: { shape: SHAPE.pulse, filterKind: FILTER.ladderLp, unison: 2, detuneCents: 7, subLevel: 0.2, cutoffHz: 2000, resonance: 0.28, envAmount: 1400, keyTrack: 0.55, ampAttack: 0.015, ampSustain: 0.88, ampRelease: 0.22, fltSustain: 0.6, lfoRate: 0.9, lfoToPwm: 0.34, chorusMix: 0.35, reverbMix: 0.28, gain: 0.227 } },
  "whistle-lead": { label: "Whistle lead", group: "lead",
    blurb: "Almost a sine, with vibrato. Sits on top of everything.",
    params: { shape: SHAPE.triangle, filterKind: FILTER.svfLp, unison: 1, subLevel: 0.05, cutoffHz: 3200, resonance: 0.08, drive: 1.0, envAmount: 400, keyTrack: 0.7, ampAttack: 0.05, ampSustain: 0.9, ampRelease: 0.25, fltSustain: 0.8, lfoRate: 5.8, lfoToPitch: 16, reverbMix: 0.45, delayMix: 0.2, gain: 0.126 } },
  "warm-pad": { label: "Warm pad", group: "pad",
    blurb: "Slow, thick, unhurried.",
    params: { shape: SHAPE.saw, filterKind: FILTER.ladderLp, unison: 3, detuneCents: 19, subLevel: 0.28, noiseLevel: 0.03, cutoffHz: 620, resonance: 0.18, drive: 1.1, envAmount: 1500, keyTrack: 0.45, ampAttack: 0.55, ampDecay: 1.2, ampSustain: 0.8, ampRelease: 1.3, fltAttack: 0.7, fltDecay: 1.4, fltSustain: 0.55, fltRelease: 1.2, velToCutoff: 900, chorusMix: 0.85, chorusRate: 0.42, chorusDepth: 4.2, reverbMix: 0.55, reverbSize: 0.85, reverbPredelay: 30, gain: 0.366 , stereoWidth: 0.85 } },
  "string-pad": { label: "String pad", group: "pad",
    blurb: "Ensemble machine. Wide and slightly seasick.",
    params: { shape: SHAPE.saw, filterKind: FILTER.svfLp, unison: 5, detuneCents: 22, subLevel: 0.15, cutoffHz: 1500, resonance: 0.12, drive: 1.0, envAmount: 700, keyTrack: 0.5, ampAttack: 0.35, ampSustain: 0.85, ampRelease: 1.0, fltAttack: 0.4, fltSustain: 0.7, chorusMix: 0.95, chorusRate: 0.55, chorusDepth: 5.5, reverbMix: 0.5, reverbSize: 0.8, gain: 0.306 , stereoWidth: 0.95 } },
  "choir-pad": { label: "Choir pad", group: "pad",
    blurb: "Pulse width drift and a soft top. Vowel-like.",
    params: { shape: SHAPE.pulse, filterKind: FILTER.svfLp, unison: 3, detuneCents: 14, pulseWidth: 0.44, subLevel: 0.2, noiseLevel: 0.04, cutoffHz: 1100, resonance: 0.2, envAmount: 800, keyTrack: 0.5, ampAttack: 0.5, ampSustain: 0.85, ampRelease: 1.1, fltAttack: 0.6, fltSustain: 0.6, lfoRate: 0.28, lfoToPwm: 0.26, chorusMix: 0.7, reverbMix: 0.6, reverbSize: 0.85, gain: 0.119 , stereoWidth: 0.8 } },
  "sweep-pad": { label: "Sweep pad", group: "pad",
    blurb: "The filter is the movement. Very slow.",
    params: { shape: SHAPE.saw, filterKind: FILTER.ladderLp, unison: 3, detuneCents: 17, subLevel: 0.25, cutoffHz: 400, resonance: 0.5, drive: 1.3, envAmount: 900, ampAttack: 0.6, ampSustain: 0.85, ampRelease: 1.4, fltAttack: 0.8, fltSustain: 0.6, lfoRate: 0.12, lfoToCutoff: 2200, chorusMix: 0.5, reverbMix: 0.55, reverbSize: 0.9, gain: 0.459 } },
  "glass-pad": { label: "Glass pad", group: "pad",
    blurb: "Highpassed and thin. Sits above a mix, never in it.",
    params: { shape: SHAPE.saw, filterKind: FILTER.svfHp, unison: 4, detuneCents: 16, subLevel: 0, cutoffHz: 900, resonance: 0.35, drive: 1.1, envAmount: 600, keyTrack: 0.6, ampAttack: 0.4, ampSustain: 0.8, ampRelease: 1.1, fltAttack: 0.5, fltSustain: 0.6, chorusMix: 0.6, reverbMix: 0.65, reverbSize: 0.9, reverbDamp: 9000, gain: 0.663 , stereoWidth: 0.85 } },
  "dark-pad": { label: "Dark pad", group: "pad",
    blurb: "Everything above the fundamental removed. Ominous.",
    params: { shape: SHAPE.saw, filterKind: FILTER.ladderLp, unison: 3, detuneCents: 21, subLevel: 0.5, cutoffHz: 260, resonance: 0.22, drive: 1.4, envAmount: 500, keyTrack: 0.3, ampAttack: 0.7, ampSustain: 0.85, ampRelease: 1.6, fltAttack: 0.9, fltSustain: 0.5, chorusMix: 0.4, reverbMix: 0.6, reverbSize: 0.95, reverbDamp: 2200, gain: 0.252 } },
  "halo-pad": { label: "Halo pad", group: "pad",
    blurb: "Mostly reverb. More space than sound.",
    params: { shape: SHAPE.triangle, filterKind: FILTER.svfLp, unison: 4, detuneCents: 11, subLevel: 0.1, noiseLevel: 0.05, cutoffHz: 1800, resonance: 0.15, envAmount: 600, ampAttack: 0.9, ampSustain: 0.7, ampRelease: 1.8, fltAttack: 1.0, fltSustain: 0.7, chorusMix: 0.5, reverbMix: 0.8, reverbSize: 0.98, reverbPredelay: 45, delayMix: 0.2, delayTime: 0.5, gain: 0.227 , stereoWidth: 0.9 } },
  "notch-pad": { label: "Notch pad", group: "pad",
    blurb: "A hole swept through the middle. Phaser-adjacent.",
    params: { shape: SHAPE.saw, filterKind: FILTER.svfNotch, unison: 3, detuneCents: 15, subLevel: 0.2, cutoffHz: 800, resonance: 0.5, drive: 1.2, envAmount: 400, ampAttack: 0.45, ampSustain: 0.85, ampRelease: 1.2, fltSustain: 0.6, lfoRate: 0.18, lfoToCutoff: 1600, reverbMix: 0.5, gain: 0.213 } },
  "wind": { label: "Wind", group: "pad",
    blurb: "No oscillator at all — pink noise through a slow, resonant sweep.",
    params: { oscLevel: 0, subLevel: 0, noiseLevel: 1, noiseColor: 1,
      filterKind: FILTER.svfBp, cutoffHz: 420, resonance: 0.55, drive: 1.0,
      envAmount: 500, keyTrack: 0.6, lfo2Rate: 0.35, lfo2ToCutoff: 900,
      ampAttack: 0.7, ampDecay: 1.5, ampSustain: 0.75, ampRelease: 1.4,
      fltAttack: 0.9, fltDecay: 2.0, fltSustain: 0.6, fltRelease: 1.5,
      reverbMix: 0.5, reverbSize: 0.85, stereoWidth: 0, gain: 0.85 } },

  "breath-pad": { label: "Breath pad", group: "pad",
    blurb: "Pink noise blended under the strings — the air a real ensemble has.",
    params: { shape: SHAPE.saw, filterKind: FILTER.svfLp, unison: 4, detuneCents: 14,
      oscLevel: 0.85, noiseLevel: 0.45, noiseColor: 1,
      cutoffHz: 900, resonance: 0.2, drive: 1.1, envAmount: 900, keyTrack: 0.5,
      ampAttack: 0.5, ampDecay: 1.4, ampSustain: 0.8, ampRelease: 1.2,
      fltAttack: 0.6, fltDecay: 1.8, fltSustain: 0.55, fltRelease: 1.2,
      chorusMix: 0.35, reverbMix: 0.4, reverbSize: 0.8, stereoWidth: 0.9, gain: 0.256 } },

  "atmosphere": { label: "Atmosphere", group: "pad",
    blurb: "Noise and a narrow band. Barely a note at all.",
    params: { shape: SHAPE.triangle, filterKind: FILTER.svfBp, unison: 2, detuneCents: 25, subLevel: 0.05, noiseLevel: 0.55, cutoffHz: 1100, resonance: 0.6, envAmount: 900, ampAttack: 1.1, ampSustain: 0.75, ampRelease: 2.0, fltAttack: 1.2, fltSustain: 0.6, lfoRate: 0.09, lfoToCutoff: 1200, reverbMix: 0.85, reverbSize: 0.98, reverbPredelay: 60, gain: 0.85 , stereoWidth: 0.9 } },
  "rain": { label: "Rain", group: "pad",
    blurb: "Filtered noise, moving. No pitch to speak of.",
    params: { shape: SHAPE.triangle, filterKind: FILTER.svfBp, unison: 1, subLevel: 0, noiseLevel: 0.9, cutoffHz: 2200, resonance: 0.72, envAmount: 600, keyTrack: 0.8, ampAttack: 0.5, ampSustain: 0.7, ampRelease: 1.2, fltSustain: 0.7, lfoRate: 0.45, lfoToCutoff: 1800, reverbMix: 0.6, delayMix: 0.3, delayTime: 0.4, gain: 0.471 , stereoWidth: 0.7 } },
  "pluck": { label: "Pluck", group: "pluck",
    blurb: "Short, bright, no sustain. The default that just works.",
    params: { shape: SHAPE.saw, filterKind: FILTER.ladderLp, unison: 2, detuneCents: 5, subLevel: 0.3, cutoffHz: 900, resonance: 0.55, drive: 1.3, envAmount: 3600, keyTrack: 0.45, ampDecay: 0.26, ampSustain: 0, ampRelease: 0.12, fltDecay: 0.13, fltSustain: 0, velToCutoff: 2200, reverbMix: 0.22, delayMix: 0.22, delayTime: 0.125, gain: 0.85 } },
  "wow-pluck": { label: "Wow pluck", group: "pluck",
    blurb: "Each note gets its own filter sweep, starting when you play it.",
    params: { shape: SHAPE.saw, filterKind: FILTER.ladderLp, unison: 2, detuneCents: 7,
      subLevel: 0.2, cutoffHz: 500, resonance: 0.6, drive: 1.5, envAmount: 1200,
      keyTrack: 0.4, lfo2Rate: 3.2, lfo2ToCutoff: 2200,
      ampAttack: 0.003, ampDecay: 0.9, ampSustain: 0.3, ampRelease: 0.25,
      fltDecay: 0.4, fltSustain: 0.4, velToCutoff: 1600, stereoWidth: 0.4,
      reverbMix: 0.3, delayMix: 0.2, gain: 0.497 } },

  "bell-pluck": { label: "Bell pluck", group: "pluck",
    blurb: "Glassy and short, with a long tail behind it.",
    params: { shape: SHAPE.pulse, filterKind: FILTER.svfBp, unison: 2, detuneCents: 8, subLevel: 0.1, cutoffHz: 1600, resonance: 0.55, drive: 1.1, envAmount: 2600, keyTrack: 0.8, ampDecay: 0.5, ampSustain: 0, ampRelease: 0.3, fltDecay: 0.2, fltSustain: 0, reverbMix: 0.55, reverbSize: 0.8, delayMix: 0.3, delayTime: 0.33, gain: 0.619 } },
  "e-piano": { label: "Electric keys", group: "pluck",
    blurb: "Soft attack, woody body, medium decay.",
    params: { shape: SHAPE.triangle, filterKind: FILTER.ladderLp, unison: 2, detuneCents: 4, subLevel: 0.35, cutoffHz: 1300, resonance: 0.2, drive: 1.5, envAmount: 1600, keyTrack: 0.5, ampAttack: 0.004, ampDecay: 0.8, ampSustain: 0.25, ampRelease: 0.3, fltDecay: 0.5, fltSustain: 0.15, velToCutoff: 2600, chorusMix: 0.3, reverbMix: 0.25, gain: 0.381 } },
  "clav": { label: "Clav", group: "pluck",
    blurb: "Narrow pulse, high resonance, gone instantly.",
    params: { shape: SHAPE.pulse, filterKind: FILTER.svfBp, unison: 1, pulseWidth: 0.22, subLevel: 0.15, cutoffHz: 1600, resonance: 0.62, drive: 1.8, envAmount: 2600, keyTrack: 0.6, ampDecay: 0.22, ampSustain: 0.05, ampRelease: 0.1, fltDecay: 0.12, fltSustain: 0.1, velToCutoff: 2800, gain: 0.783 } },
  "mallet": { label: "Mallet", group: "pluck",
    blurb: "Struck and wooden. Almost no harmonics after the hit.",
    params: { shape: SHAPE.triangle, filterKind: FILTER.svfLp, unison: 1, subLevel: 0.2, cutoffHz: 1400, resonance: 0.3, drive: 1.0, envAmount: 3000, keyTrack: 0.7, ampAttack: 0.001, ampDecay: 0.35, ampSustain: 0, ampRelease: 0.15, fltDecay: 0.07, fltSustain: 0, velToCutoff: 2600, reverbMix: 0.3, gain: 0.556 } },
  "stab-key": { label: "Stab key", group: "pluck",
    blurb: "Chord stab. Hits hard, stops dead.",
    params: { shape: SHAPE.saw, filterKind: FILTER.ladderLp, unison: 3, detuneCents: 10, subLevel: 0.2, cutoffHz: 700, resonance: 0.45, drive: 1.7, envAmount: 3800, ampAttack: 0.004, ampDecay: 0.3, ampSustain: 0, ampRelease: 0.12, fltDecay: 0.16, fltSustain: 0, velToCutoff: 2600, reverbMix: 0.3, gain: 0.85 } },
  "crystal": { label: "Crystal", group: "pluck",
    blurb: "Tiny, bright, and repeating away into the distance.",
    params: { shape: SHAPE.saw, filterKind: FILTER.svfHp, unison: 2, detuneCents: 9, subLevel: 0, cutoffHz: 900, resonance: 0.45, envAmount: 2400, keyTrack: 0.9, ampAttack: 0.001, ampDecay: 0.3, ampSustain: 0, ampRelease: 0.25, fltDecay: 0.18, fltSustain: 0, reverbMix: 0.6, reverbSize: 0.9, reverbDamp: 11000, delayMix: 0.4, delayTime: 0.28, delayFeedback: 0.5, gain: 0.85 } },
  "brass-stab": { label: "Brass stab", group: "brass",
    blurb: "Filter env does the work. Hit it hard.",
    params: { shape: SHAPE.saw, filterKind: FILTER.ladderLp, unison: 3, detuneCents: 13, subLevel: 0.22, cutoffHz: 480, resonance: 0.48, drive: 1.8, envAmount: 4200, ampAttack: 0.012, ampDecay: 0.22, ampSustain: 0.68, ampRelease: 0.26, fltAttack: 0.018, fltDecay: 0.26, fltSustain: 0.22, velToCutoff: 2800, lfoRate: 4.5, lfoToPitch: 3, chorusMix: 0.35, reverbMix: 0.28, gain: 0.449 } },
  "brass-section": { label: "Brass section", group: "brass",
    blurb: "Slower swell, wider. Several players, not one.",
    params: { shape: SHAPE.saw, filterKind: FILTER.ladderLp, unison: 5, detuneCents: 18, subLevel: 0.2, cutoffHz: 560, resonance: 0.4, drive: 1.6, envAmount: 3400, ampAttack: 0.07, ampDecay: 0.4, ampSustain: 0.8, ampRelease: 0.35, fltAttack: 0.09, fltDecay: 0.5, fltSustain: 0.5, velToCutoff: 2200, lfoRate: 4.2, lfoToPitch: 5, chorusMix: 0.4, reverbMix: 0.4, reverbSize: 0.7, gain: 0.343 , stereoWidth: 0.7 } },
  "hoover": { label: "Hoover", group: "brass",
    blurb: "Detuned pulse with a downward sweep. Unmistakable.",
    params: { shape: SHAPE.pulse, filterKind: FILTER.ladderLp, unison: 5, detuneCents: 44, pulseWidth: 0.28, subLevel: 0.35, cutoffHz: 320, resonance: 0.72, drive: 2.6, envAmount: 5200, glide: 0.12, ampAttack: 0.01, ampSustain: 0.85, ampRelease: 0.25, fltDecay: 0.9, fltSustain: 0.18, lfoRate: 0.6, lfoToPwm: 0.2, reverbMix: 0.35, delayMix: 0.2, gain: 0.14 , stereoWidth: 0.8 } },
  "horn-swell": { label: "Horn swell", group: "brass",
    blurb: "Slow in, slow out. Wants to be held.",
    params: { shape: SHAPE.saw, filterKind: FILTER.svfLp, unison: 4, detuneCents: 12, subLevel: 0.3, cutoffHz: 700, resonance: 0.25, drive: 1.4, envAmount: 2000, ampAttack: 0.3, ampSustain: 0.9, ampRelease: 0.6, fltAttack: 0.35, fltSustain: 0.7, lfoRate: 3.8, lfoToPitch: 4, chorusMix: 0.3, reverbMix: 0.45, reverbSize: 0.8, gain: 0.149 } },
  "sci-fi": { label: "Sci-fi", group: "lead",
    blurb: "Deep pitch modulation. Not really a musical instrument.",
    params: { shape: SHAPE.pulse, filterKind: FILTER.svfBp, unison: 2, detuneCents: 20, pulseWidth: 0.3, subLevel: 0.1, noiseLevel: 0.1, cutoffHz: 1400, resonance: 0.7, drive: 1.6, envAmount: 2000, ampAttack: 0.02, ampSustain: 0.8, ampRelease: 0.4, fltSustain: 0.5, lfoRate: 6.5, lfoToPitch: 45, lfoToCutoff: 900, reverbMix: 0.5, delayMix: 0.35, delayFeedback: 0.5, gain: 0.178 } },
};

/** Demo pattern groups, in menu order. */
export const GROUPS = ["bass", "lead", "pad", "pluck", "brass"];

export function applyPreset(engine, name) {
  const p = PRESETS[name];
  if (!p) throw new Error(`unknown preset: ${name}`);
  // Merged over DEFAULTS: nothing carries over from the previously selected patch.
  for (const [k, v] of Object.entries({ ...DEFAULTS, ...p.params })) engine.setParam(k, v);
  return p;
}
