#!/usr/bin/env node
// Generate the declaration file from the runtime parameter metadata.
//
// `parameters.js` is the only editable definition of ids, defaults, ranges, units, and
// enum values. Committing the generated declaration makes editor tooling work directly
// from the source tree; `--check` makes drift a build and CI failure.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { PARAMETERS } from "../packages/core/src/parameters.js";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const output = join(root, "packages/core/src/parameters.d.ts");

const literal = (value) => JSON.stringify(value);
const enumType = (values) => {
  const members = Object.entries(values).map(([name, value]) => `readonly ${name}: ${value};`);
  return `{ ${members.join(" ")} }`;
};

const lines = [
  "// Generated by scripts/gen_parameters.mjs from parameters.js. Do not edit.",
  "export interface ParameterDefinition {",
  "  readonly id: number;",
  "  /** Value applied for this field when a preset omits it. */",
  "  readonly default: number;",
  "  readonly min: number;",
  "  readonly max: number;",
  "  readonly step: number;",
  "  readonly unit: string;",
  "  readonly values?: Readonly<Record<string, number>>;",
  "  /** Preferred playground ceiling; the control expands for a preset above it. */",
  "  readonly editorMax?: number;",
  "}",
  "",
  `export declare const SHAPE: ${enumType(PARAMETERS.shape.values)};`,
  `export declare const FILTER: ${enumType(PARAMETERS.filterKind.values)};`,
  "",
  "export declare const PARAMETERS: {",
];

for (const [name, definition] of Object.entries(PARAMETERS)) {
  const fields = [
    `readonly id: ${definition.id};`,
    `readonly default: ${literal(definition.default)};`,
    `readonly min: ${literal(definition.min)};`,
    `readonly max: ${literal(definition.max)};`,
    `readonly step: ${literal(definition.step)};`,
    `readonly unit: ${literal(definition.unit)};`,
  ];
  if (definition.values) fields.push(`readonly values: ${enumType(definition.values)};`);
  if (definition.editorMax !== undefined) fields.push(`readonly editorMax: ${literal(definition.editorMax)};`);
  lines.push(`  readonly ${name}: { ${fields.join(" ")} };`);
}

lines.push(
  "};",
  "",
  "/** Patch parameter names accepted by `Engine.setParam`. */",
  "export type ParamName = keyof typeof PARAMETERS;",
  "",
  "export declare const PARAM: {",
  "  readonly [Name in ParamName]: (typeof PARAMETERS)[Name][\"id\"];",
  "};",
  "",
  "export declare const PARAM_DEFAULTS: {",
  "  readonly [Name in ParamName]: (typeof PARAMETERS)[Name][\"default\"];",
  "};",
  "",
);

const generated = lines.join("\n");
const current = (() => { try { return readFileSync(output, "utf8"); } catch { return ""; } })();

if (process.argv.includes("--check")) {
  if (current !== generated) {
    console.error("PARAMETER METADATA FAIL — packages/core/src/parameters.d.ts is stale");
    console.error("Run: node scripts/gen_parameters.mjs");
    process.exit(1);
  }
  console.log(`parameter metadata OK — ${Object.keys(PARAMETERS).length} definitions and declarations agree`);
} else if (current !== generated) {
  writeFileSync(output, generated);
  console.log(`generated packages/core/src/parameters.d.ts (${Object.keys(PARAMETERS).length} parameters)`);
} else {
  console.log("parameter declarations already current");
}
