import { chromium } from "playwright";
import { spawn } from "node:child_process";
const PORT = 8181;
const server = spawn("python3", ["-m", "http.server", String(PORT)], { stdio: "ignore" });
await new Promise(r => setTimeout(r, 700));
const b = await chromium.launch({ args: ["--autoplay-policy=no-user-gesture-required"] });
const p = await b.newPage({ viewportSize: { width: 1000, height: 900 }, deviceScaleFactor: 2 });
await p.goto(`http://localhost:${PORT}/apps/playground/`);
await p.click("#start");
await p.waitForFunction(() => document.getElementById("status").textContent.startsWith("ready"), null, { timeout: 15000 });
await p.evaluate(() => { for (const n of [48,52,55,60]) document.querySelector(`[data-note="${n}"]`)?.classList.add("on"); });
await p.screenshot({ path: "/tmp/playground.png", fullPage: true });
console.log("status:", await p.textContent("#status"));
await b.close(); server.kill();
